author: CeramicTitan
description: Keeps staff play time.
main: me.ceramictitan.admintracker.AdminTracker
name: AdminTracker
url: 
version: 1.1.6
commands:
    timekeeper:
      description: base command
    
permissions:
    at.clock:
      description: Players with this permission clock in and out.
    at.notify:
      description: Announces to the server when a player with this permission joins. Intended for announcing when Moderators join.
      default: false
    at.check:
      description: Players with this permission can check clock in and clock out statuses
      default: false